typography_spectrum: 0.20745
color:
  brandColors:
    - '#030303'
    - '#ededed'
    - '#474747'
    - '#797979'
    - '#acacac'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50186
analytics:
  google: UA-75321215-1
  facebook: 617785341705529
  twitter: null
author:
  name: chalon
  email: contact@betty-lascene.fr
  url: 'http://betty-lascene.fr'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bf1c30c6-4a26-4fe6-832e-8f9abcac0431.png
name: Betty Lascene & les Gangsters
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Video
    url: 'https://www.youtube.com/watch?v=STLFSiigZY0'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/BETTYLASCENE'
    type: external
  - name: CONTACT
    id: ca3efbb8-6306-442b-a572-4bca85f0fc2e
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e1d30937-d2b2-4fb2-9bf5-cee1cdf3e6d9.png
title: 'Music, Events & Airstream'
purpose: []
