typography_spectrum: 0.20745
color:
  brandColors:
    - '#030303'
    - '#ededed'
    - '#474747'
    - '#797979'
    - '#acacac'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50186
analytics:
  google: UA-75321215-1
  facebook: 617785341705529
  twitter: null
author:
  name: chalon
  email: contact@betty-lascene.fr
  url: 'http://betty-lascene.fr'
name: 'DUO MUSICIENS COUNTRY ROCK  AIRSTREAM FRANCE caravane américaine '
cta:
  domain: null
  bucket: null
  version: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/85278151-457b-442b-9bf6-7db50b620721.ico'
title: 'BETTY LASCENE & LES GANGSTERS'
purpose: []
