typography_spectrum: 0.20745
color:
  brandColors:
    - '#030303'
    - '#ededed'
    - '#474747'
    - '#797979'
    - '#acacac'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50186
analytics:
  google: UA-75321215-1
  facebook: "<!-- Facebook Pixel Code --> <script> !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod? n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n; n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0; t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window, document,'script','https://connect.facebook.net/en_US/fbevents.js');  fbq('init', '617785341705529'); fbq('track', \"PageView\");</script> <noscript><img height=\"1\" width=\"1\" style=\"display:none\" src=\"https://www.facebook.com/tr?id=617785341705529&ev=PageView&noscript=1\" /></noscript> <!-- End Facebook Pixel Code -->"
  twitter: null
author:
  name: chalon
  email: contact@betty-lascene.fr
  url: 'http://betty-lascene.fr'
name: 'DUO MUSICIENS COUNTRY ROCK  AIRSTREAM FRANCE caravane américaine '
cta:
  domain: null
  bucket: null
  version: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/85278151-457b-442b-9bf6-7db50b620721.ico'
title: 'BETTY LASCENE & LES GANGSTERS'
purpose: []
