name: 'BETTY LASCENE & LES GANGSTERS'
favicon: null
layout_spectrum: 0.74532
typography_spectrum: 0.20745
title: 'BETTY-LASCENE & LES GANGSTERS'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75321215-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#ededed'
    - '#474747'
    - '#797979'
    - '#acacac'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
